---
format: html
title: "Tidyverse"
author: "Preethi Aranala"
---

# SALES ANALYSIS ----

# 1.0 Loading necessary libraries ----

```{r}
#| eval: false
#| 

library(tidyverse)
library(readxl)
```

# 2.0 Importing Files ----

```{r}
#| eval: false
#| 

bikes_tbl <- read_excel("00_raw_data/01_bike_sales/01_raw_data/bikes.xlsx")

bikeshops_tbl <- read_excel("00_raw_data/01_bike_sales/01_raw_data/bikeshops.xlsx")

orderlines_tbl <- read_excel("00_raw_data/01_bike_sales/01_raw_data/orderlines.xlsx")
```

# 3.0 Examining Data ----

```{r}
#| eval: false
#| 
bikes_tbl %>% glimpse()
bikeshops_tbl %>% glimpse()
orderlines_tbl %>% glimpse()

```

# 4.0 Joining Data ----

```{r}
#| eval: false
bike_orderlines_joined_tbl <- orderlines_tbl %>%
        left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>%
        left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))

bike_orderlines_joined_tbl %>% glimpse()

```

# 5.0 Wrangling Data ----

```{r}
#| eval: false
#| 
bike_orderlines_wrangled_tbl <- bike_orderlines_joined_tbl %>%
  separate(col    = location,
           into   = c("city", "state"),
           sep    = ",") %>%
  mutate(total.price = price * quantity) %>%
  select(-...1, -gender) %>%
  select(-ends_with(".id")) %>%
  bind_cols(bike_orderlines_joined_tbl %>% select(order.id)) %>% 
  select(order.id, contains("order"), contains("model"), contains("location"),
         price, quantity, total.price,
         everything()) %>%
  rename(bikeshop = name) %>%
  set_names(names(.) %>% str_replace_all("\\.", "_"))

```

# 6.0 Business Insights ----

# 6.1 Sales by Location ----

# Step 1 - Manipulate

```{r}
#| eval: false
#| 

sales_by_loc_tbl <- bike_orderlines_wrangled_tbl %>%
group_by(state) %>% 
summarize(sales = sum(total_price)) %>%
mutate(revenue = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

sales_by_loc_tbl

```

# Step 2 - Visualize

```{r}
#| eval: false
#| 

sales_by_loc_tbl %>%
ggplot(aes(x = state, y = sales)) +
geom_col(fill = "#2DC6D6") + 
geom_label(aes(label = revenue)) + 
scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
theme(axis.text.x = element_text(angle = 45, hjust = 1))+                 labs(
    title    = "Revenue by State",
    x = "", # Override defaults for x and y
    y = "Revenue"
  )

```

# 6.2 Sales by State and Year ----

```{r}
#| eval: false
#| 

library(lubridate)
```

# Step 1 - Manipulate

```{r}
#| eval: false
#| 
sales_by_year_tbl <- bike_orderlines_wrangled_tbl %>%
select(state, order_date, total_price) %>%
mutate(year = year(order_date)) %>%
group_by(state, year) %>% 
summarize(sales = sum(total_price)) %>%
mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))
sales_by_year_tbl
```

# Step 2 - Visualize

```{r}
#| eval: false
#| 
sales_by_year_tbl %>%
  ggplot(aes(x = year, y = sales, fill = state)) +
  geom_col() + # Run up to here to get a stacked bar plot
  facet_wrap(~ state) +
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title = "Revenue by Year and State",
    fill = "States" 
  )
```

# 7.0 Writing Files ----

```{r}
#| eval: false
#| 
library(writexl)
```

# 7.1 Excel ----

```{r}
#| eval: false
#| 
bike_orderlines_wrangled_tbl %>% 
write_xlsx("00_raw_data/01_bike_sales/02_wrangled_data/bike_orderlines.xlsx")
```

# 7.2 CSV ----

```{r}
#| eval: false
#| 

bike_orderlines_wrangled_tbl %>% 
write_csv("00_raw_data/01_bike_sales/02_wrangled_data/bike_orderlines.csv")
```

# 7.3 RDS ----

```{r}
#| eval: false
#| 
bike_orderlines_wrangled_tbl %>% 
write_rds("00_raw_data/01_bike_sales/02_wrangled_data/bike_orderlines.rds")
```
