---
format: html
title: "Data Acquisition"
author: "Preethi Aranala"
---
DATA ACQUISITION

# Challenge 2: WEBSCRAPING ----

## Libraries ----

```{r}
#| eval: false
#| 

library(tidyverse)
library(readr)     
library(xopen)    
library(glue)     
library(stringi)   
library(xml2)
library(knitr)
library(rvest)

```

## Collect Product Categories

```{r}
#| eval: false
#| 

url_home          <- "https://www.rosebikes.com/bikes/mtb/cross-country"
xopen(url_home)
html_home         <- read_html(url_home)

bike_category_tbl <- html_home %>%
  html_nodes(css = "a.btn.btn--primary.btn--block.catalog-category-bikes__button") %>%
  html_attr('href') %>%
  enframe(name = "position", value = "subdirectory") %>%
  mutate(
    url = glue("https://www.rosebikes.com{subdirectory}")
  ) %>%
  distinct(url)


kable(head(bike_category_tbl))
```

## Collect Bike Category and Price----

```{r}
#| eval: false
#| 

bike_type_tbl <- tibble()

for (url in bike_category_tbl$url) {
  xopen(url)
  html_bike_type <- read_html(url)
  
  model_name <- html_bike_type %>%
    html_nodes(css = ".catalog-category-model__title") %>%
    html_text() 
  
  
  price <- html_bike_type %>%
    html_nodes(css = ".catalog-category-model__price-current-value") %>%
    html_text() %>%
    str_remove_all("[^0-9.]") %>%
    as.numeric()
  
  bike_type_tbl <- bind_rows(bike_type_tbl, tibble(model_name, price)) %>%
    distinct(model_name, .keep_all = TRUE)
  
}
kable(head(bike_type_tbl))
```

# Challenge 1: API

## Libraries
```{r}
#| eval: false
#| 

library(dplyr)
library(httr)
library(jsonlite)

```

## API Key Retrieval
```{r}
#| eval: false
#| 
api_key <- Sys.getenv("MY_API_KEY")
if (is.na(api_key)) {
  stop("API key not found in the .Renviron file.")
}

```
## Open Weather Map API URL
```{r}
#| eval: false
#| 

weather_response <- GET(glue("https://api.openweathermap.org/data/2.55/weather?lat=44.34&lon=10.99&appid={api_key}"))

```

## Response Extraction
```{r}
#| eval: false
#| 

current_weather_data <- content(weather_response, as = "text")
current_weather <- fromJSON(current_weather_data)

temperature_celsius <- round(current_weather$main$temp - 273.15, 2)
humidity_percentage <- current_weather$main$humidity
description <- current_weather$weather[[1]]$description

```
## Data Manipulation

```{r}
#| eval: false
#| 
cat("Current Weather in:", description, "\n")
cat("Temperature:", temperature_celsius, "°C\n")
cat("Humidity:", humidity_percentage, "%\n")

```
