---
title: "Data Wrangling"
author: "Preethi Aranala"
---
# LIBRARIES ----

```{r}
#| eval: false
#| 
library(vroom)
library(readr)
library(ggplot2)
library(lubridate)
```

# ASSIGNING COLUMN TYPES
```{r}
#| eval: false
#| 

col_types <- list(
  id = col_character(),
  patent_id = col_character(),
  assignee_id = col_character(),
  mainclass_id = col_character(),
  type = col_character(),
  number = col_character(),
  country = col_character(),
  organization = col_character(),
  date = col_date("%Y-%m-%d"),
  abstract = col_character(),
  title = col_character(),
  kind = col_character(),
  num_claims = col_double(),
  filename = col_character(),
  withdrawn = col_double(),
  sequence = col_integer()
)

```
# IMPORTING FILES INTO TABLES
```{r}
#| eval: false
#| 

patent_tbl <- vroom(
  file       = "00_raw_data/Patent_data_reduced/patent.tsv", 
  delim      = "\t", 
  col_types  = col_types[c("id",  "date",  "num_claims")],
  na         = c("", "NA", "NULL")
)

patent_assignee_tbl <- vroom(
  file       =  "00_raw_data/Patent_data_reduced/patent_assignee.tsv", 
  delim      = "\t", 
  col_types  = col_types[c("patent_id",   "assignee_id")],
  na         = c("", "NA", "NULL")
)

assignee_tbl        <- vroom(
  file       = "00_raw_data/Patent_data_reduced/assignee.tsv", 
  delim      = "\t", 
  col_types  = col_types[c("id",  "type",  "organization")],
  na         = c("", "NA", "NULL")
)

uspc_tbl            <- vroom(
  file       =  "00_raw_data/Patent_data_reduced/uspc.tsv", 
  delim      = "\t", 
  col_types  = col_types[c("patent_id",  "mainclass_id",                                              "sequence")],
  na         = c("", "NA", "NULL")
)
```

# Question 1
## Manipulating the data        
```{r}
#| eval: false
#| 

patent_assignee_dt <- merge(patent_assignee_tbl, assignee_tbl, by.x = "assignee_id", by.y = "id", all.x = T) %>%
  filter(type == 2) %>% 
  group_by(organization) %>%
  summarize(quantity = n()) %>%
  arrange(desc(quantity))
```

## Visualizing the data       
```{r}
#| eval: false
#| 
patent_assignee_dt %>%
  slice(1:10) %>%
  ggplot(aes(x=organization, y=quantity)) +
  geom_label(aes(label = quantity), vjust = -0.2) + 
  geom_col(fill = "#2DC6D6") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+ 
  labs(
    title    = "Patents by Top US Companies",
    x = "Top 10 US Companies", # Override defaults for x and y
    y = "Quantity"
  )
``` 
# Question 2
## Manipulating the data
```{r}
#| eval: false
#| 
patent_dt2 <- patent_tbl %>%
  left_join(patent_assignee_tbl, by = c("id" = "patent_id")) %>%
  left_join(assignee_tbl, by = c("assignee_id" = "id")) %>%
  filter(type == 2 & date>= "2014-08-01" & date<= "2014-08-31") %>% 
  group_by(organization) %>%
  summarise(quantity = n()) %>%
  ungroup() %>%
  arrange(desc(quantity))
```        
## Visualizing the data       
```{r}
#| eval: false
#| 

patent_dt2 %>%
  slice(1:10) %>%
  ggplot(aes(x=organization, y=quantity)) +
  geom_label(aes(label = quantity), vjust = -0.2) + 
  geom_col(fill = "#2DC6D6") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+ 
  labs(
    title    = "Most Patents by Top US Companies in August 2014",
    x = "Top 10 US Companies", # Override defaults for x and y
    y = "Quantity"
  )
```
# Question 3
## Manipulating the data
```{r}
#| eval: false
#| 

patent_dt3 <- patent_assignee_tbl %>%
  left_join(assignee_tbl, by = c("assignee_id" = "id"), relationship = "many-to-many") %>%
  left_join(uspc_tbl, by = c("patent_id" = "patent_id"), relationship = "many-to-many")

top_10_companies <- patent_dt3 %>%
  group_by(organization) %>%
  summarise(num_patents = n()) %>%
  top_n(10, num_patents)

top_5_USPTO <- patent_dt3 %>%
  filter(organization %in% top_10_companies$organization) %>%
  group_by(mainclass_id) %>%
  summarise(num_patents_per_mainclass = n()) %>%
  na.omit() %>%
  top_n(5,num_patents_per_mainclass)
```
## Visualizing the data
```{r}
#| eval: false
#| 

top_5_USPTO %>%
  ggplot(aes(x=mainclass_id, y=num_patents_per_mainclass)) +
  geom_label(aes(label = num_patents_per_mainclass), vjust = -0.2) + 
  geom_col(fill = "#2DC6D6") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+ 
  labs(
    title    = "Top 5 USPTO Classes by Top 10 Companies",
    x = "Main Class ID", # Override defaults for x and y
    y = "Quantity"
  )

```


